apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-devops-us-deployment
  namespace: kubernetes-cluster-surender
  labels:
    app: nagp-devops-us-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nagp-devops-us-pod
  template:
    metadata:
      labels:
        app: nagp-devops-us-pod
    spec:
      containers:
        - name: nagp-devops-us-container
          image: surender3010/i-surender-master:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_FROMCONFIGMAP
              valueFrom:
                configMapKeyRef:
                  name: nagp-devops-us-configmap
                  key: database
            - name: DATABASE_SERVER_FROMCONFIGMAP
              valueFrom:
                configMapKeyRef:
                  name: nagp-devops-us-configmap
                  key: database_server
            - name: DATABASE_USERNAME_FROM_SECRET
              valueFrom:
                secretKeyRef:
                  name: nagp-devops-us-secret
                  key: username
              - name: DATABASE_PASSWORD_FROM_SECRET
              valueFrom:
                secretKeyRef:
                  name: nagp-devops-us-secret
                  key: password
