apiVersion: v1
kind: Service
metadata:
  name: nagp-devops-us-service
	namespace: kubernetes-cluster-surender
spec:
  type: LoadBalancer
  selector:
    app: nagp-devops-us-pod
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 80